// Dummy Data for Restaurant Cards
const resList = [
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Dominos",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "KFC",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "McDonalds",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Kababjees",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Ridan house of mandi",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Mandi House",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Havabite",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Al-Habib Restaurant",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Pie in the sky",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Gloria Jeans",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Karachi Broast",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Burger o clock",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Cluckys",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
];

export default resList;
