// Dummy Data for Restaurant Cards
const resList = [
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 1",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 2",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 3",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 4",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 5",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 6",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 7",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 8",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 9",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 10",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 11",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 12",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
	{
		id: Math.floor(Math.random() * 999),
		image_url: "https://images.deliveryhero.io/image/fd-pk/LH/hwd6-listing.jpg",
		res_title: "Res Title 13",
		res_rating: (Math.random() * 5).toFixed(2),
		res_deliveryTime: Math.floor(Math.random() * 46),
		res_cuisines: ["Burgers", "Steaks", "Sandwiches"],
		res_location: "Hyderabad",
	},
];

export default resList;
